{% set name = "scapy" %}
{% set version = "2.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "7600d7e2383c853e5c3a6e05d37e17643beebf2b3e10d7914dffcc3bc3c6e6c5"

build:
  number: 0
  skip: True  # [py<37]
  entry_points:
    - scapy = scapy.main:interact
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=62.0.0
  run:
    - python
  run_constrained:
    - cryptography >=2.0

test:
  requires:
    - pip
  imports:
    - scapy
    - scapy.arch
    - scapy.asn1
    - scapy.contrib
    - scapy.contrib.automotive
    - scapy.contrib.automotive.bmw
    - scapy.contrib.automotive.gm
    - scapy.contrib.automotive.obd
    - scapy.contrib.automotive.obd.iid
    - scapy.contrib.automotive.obd.mid
    - scapy.contrib.automotive.obd.pid
    - scapy.contrib.automotive.obd.tid
    - scapy.contrib.scada
    - scapy.contrib.scada.iec104
    - scapy.layers
    - scapy.layers.tls
    - scapy.layers.tls.crypto
    - scapy.modules
    - scapy.tools
  commands:
    - scapy -h
    - pip check

about:
  home: https://scapy.net
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Scapy: interactive packet manipulation tool'
  description: 'Scapy is a powerful Python-based interactive packet manipulation program and library.'
  doc_url: https://scapy.readthedocs.io
  dev_url: https://github.com/secdev/scapy

extra:
  recipe-maintainers:
    - gpotter2